vich_uploader:
    db_driver: orm

    mappings:
        AlbumPicture:
            uri_prefix: '%AlbumPicture%'
            upload_destination: '%kernel.project_dir%/public/upload/AlbumPicture'
            #namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        AlbumPictureImages:
            uri_prefix: '%AlbumPicture%' #/upload/AlbumPictureImages
            upload_destination: '%kernel.project_dir%/public/upload/AlbumPicture'