vich_uploader:
    db_driver: orm

    mappings:
        album_directory:
            uri_prefix: '%app.path.album_directory%'
            upload_destination: '%kernel.project_dir%/public%app.path.album_directory%'
